{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-compiler",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "databinding-compiler-7.0.3.jar",
          "url": "databinding-compiler-7.0.3.jar",
          "size": 1193240,
          "sha512": "67db133e1140d102ba547f902a652df8fe36f6603230dbd4d7fd23ca11662c2d876fb908514aa04fcff9d05be5d99b03e967e38114b2cf1b9bbc89552c9e2874",
          "sha256": "f4630ca000fb8fcbfe3ccde111129002e62ca1647a5eadd2479585324f033c5b",
          "sha1": "4ee26e5891e7b9b381db785241ab45670adb4949",
          "md5": "a44b6800bfd181423c1c09942d90f698"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-7.0.3.jar",
          "url": "databinding-compiler-7.0.3.jar",
          "size": 1193240,
          "sha512": "67db133e1140d102ba547f902a652df8fe36f6603230dbd4d7fd23ca11662c2d876fb908514aa04fcff9d05be5d99b03e967e38114b2cf1b9bbc89552c9e2874",
          "sha256": "f4630ca000fb8fcbfe3ccde111129002e62ca1647a5eadd2479585324f033c5b",
          "sha1": "4ee26e5891e7b9b381db785241ab45670adb4949",
          "md5": "a44b6800bfd181423c1c09942d90f698"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-7.0.3-javadoc.jar",
          "url": "databinding-compiler-7.0.3-javadoc.jar",
          "size": 757436,
          "sha512": "cfac390efeb90ab84697c7070dc4fcae652d9bca7c63ece2e418dc01ea46269336b4b8ba39724120a5968254bd2a4429e5b2b17e81dce3589583461ac2a1895c",
          "sha256": "bfc2cb4fb93d4c9d1bd7589e6aeee3dd4e9b5bc04e1c7a74309007a8704f8542",
          "sha1": "520e6a292567c0186914e13008bf71c41606b8fe",
          "md5": "c211e01c5922dc8eedb0cdea90f22c42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-7.0.3-sources.jar",
          "url": "databinding-compiler-7.0.3-sources.jar",
          "size": 569317,
          "sha512": "b76d602beddfef198f797922e6f8bd1a78b729f01fe198046294c3d16cee30f7951f207067ec3ccd8568d2532639517ab725f90891cdf8c38f9abd6d646880da",
          "sha256": "77ff7734e875a192d9cf7a6339ed07f4e3c1d4084665985a23d277d2dc2eb4d9",
          "sha1": "1dd08330ed8c286f1ed97eb91cf503e39e115362",
          "md5": "b2aa0c191fa9152aec414d6553d402e1"
        }
      ]
    }
  ]
}
