@@ -0,0 +1,281 @@
@startuml
'https://plantuml.com/class-diagram

SplashActivity <-- IntroActivity
SplashActivity <-- LoadingActivity
LoadingActivity <-- HomeActivity
IntroActivity <-- LoginActivity
IntroActivity <-- JoinActivity
LoginActivity <-- SplashActivity
JoinActivity <-- SplashActivity
HomeActivity <-- ProfileActivity
HomeActivity <-- AboutViewActivity
HomeActivity <-- CommActivity
HomeActivity <-- FavoriteActivity
CommActivity <--> ReviewActivity
CommActivity <-- BoardWriteActivity
ReviewActivity <-- BoardWriteActivity
BoardWriteActivity <-- BoardInsideActivity

HomeActivity <..VolunteerModel
HomeRVAdapter <..VolunteerModel
AboutViewActivity <.. FavoriteModel
FavoriteActivity <.. FavoriteModel
BoardWriteActivity <..BoardModel
BoardInsideActivity <..BoardModel
CommActivity <..BoardModel
ReviewActivity <..BoardModel

HomeActivity <.. HomeRVAdapter
HomeRVAdapter +-- HomeRVAdapter_ViewHolder
ProfileActivity <.. ProfileRVAdapter
ProfileRVAdapter +-- ProfileRVAdapter_ViewHolder
FavoriteActivity <.. FavoriteRVAdapter
FavoriteRVAdapter +-- FavoriteRVAdapter_ViewHolder
CommActivity <..CommAdapter
CommAdapter +-- CommAdapter_ViewHolder

class SplashActivity{
    -auth : FirebaseAuth
    -db : FirebaseFirestore
    -sido : String
    -gugun : String
    #onCreate(@Nullable bundle savedInstanceState) : void
    #onPause() : void
}

class LoadingActivity{
    -sido : String
    -gugun : String
    -sidocode : String
    -guguncode : String

    #onCreate(@Nullable bundle savedInstanceState) : void
}

class IntroActivity{
    #onCreate(@Nullable bundle savedInstanceState) : void
}

class LoginActivity {
    -auth : FirebaseAuth

    #onCreate(@Nullable bundle savedInstanceState) : void
}

class JoinActivity {
    -auth : FirebaseAuth
    -db : FirebaseFirestore

    #onCreate(@Nullable bundle savedInstanceState) : void
}

class HomeActivity{
    -user_phone : String
    -user_sido : String
    -user_gugun : String
    -user_email : String
    -bottombavdrawerfragment : BottomNavDrawerFragment
    -auth : FirebaseAuth
    -db : FirebaseFirestore
    -vol_time : String
    -vol_title : String
    -vol_goaltime : String
    -vol_user : String
    -sido : String
    -gugun : String
    -vol_srvcClCode : String
    -mBackWait : Long
    -items_home : MutableList

    #onCreate(@Nullable bundle savedInstanceState) : void
    #onStart() : void
    #onResume() : void
    +onBackPressed() : void
    +onCreateOptionsMenu(@Nullable Menu menu) : boolean
    +onOptionsItemSelected(@Nullable MenuItem item) : boolean
}

class HomeRVAdapter extends Adapter{
    -items : List

    +onCreateViewHolder(@NotNull ViewGroup parent, int viewType) : HomeRVAdapter.ViewHolder
    +onCreateViewHolder(ViewGroup var1, int var2) : androidx.recyclerview.widget.RecyclerView.ViewHolder
    +onBindViewHolder(@NotNull HomeRVAdapter.ViewHolder holder, int position) : void
    +onBindViewHolder(androidx.recyclerview.widget.RecyclerView.ViewHolder var1, int var2) : void
    +getItemCount() : int
    +HomeRVAdapter(@NotNull List items)
}

class HomeRVAdapter_ViewHolder extends androidx.recyclerview.widget.RecyclerView.ViewHolder{
    -vol_context : TextView
    -vol_area : TextView
    -vol_start : TextView
    -vol_end : TextView
    -vol_num : TextView
    -vol_srvcClCode : TextView

    +ViewHolder(@NotNull View itemView)
    +bindItems(@NotNull String item) : void
}
class VolunteerModel{
    +nanmmbyNm : String
    +progrmSj : String
    +progrmBgnde : String
    +progrmEndde : String
    +progrmRegistNo : String
    +vol_srvcClCode : String

    +VolunteerModel(@NotNull String nanmmbyNm, @NotNull String progrmSj, @NotNull String progrmBgnde, @NotNull String progrmEndde, @NotNull String progrmRegistNo, @NotNull String vol_srvcClCode)
}

class ProfileActivity {

    -pieChart : PieChart
    -voltime : String
    -voltitle : String
    -volgoaltime : String
    -usernickname : String
    -pnumber : String
    -name : String
    -email : String

    +getName() : String
    +setName(@Nullable String var1) : void
    +getEmail() : String
    +setEmail(@Nullable String var1) : void
    #onCreate(@Nullable bundle savedInstanceState) : void
    -initPieChart() : void
    -setDataToPieChart() : void
    +onOptionsItemSelected(@NotNull MenuItem item) : boolean
}

class ProfileRVAdapter extends Adapter{
    -items : List

    +onCreateViewHolder(@NotNull ViewGroup parent, int viewType) : ProfileRVAdapter.ViewHolder
    +onCreateViewHolder(ViewGroup var1, int var2) : androidx.recyclerview.widget.RecyclerView.ViewHolder
    +onBindViewHolder(@NotNull ProfileRVAdapter.ViewHolder holder, int position) : void
    +onBindViewHolder(androidx.recyclerview.widget.RecyclerView.ViewHolder var1, int var2) : void
    +getItemCount() : int
    +ProfileRVAdapter(@NotNull List items)
}

class ProfileRVAdapter_ViewHolder extends androidx.recyclerview.widget.RecyclerView.ViewHolder{
    -rv_text : TextView
    +ViewHolder(@NotNull View itemView)
    +bindItems(@NotNull String item) : void
}


class AboutViewActivity{
    -num1 : String
    -tel1 : String
    -title1 : String
    -starttime1 : String
    -endtime1 : String
    -auth : FirebaseAuth
    -db : FirebaseFirestore

    #onCreate(@Nullable bundle savedInstanceState) : void
    +onCreateOptionsMenu(@Nullable Menu menu) : boolean
    +onOptionsItemSelected(@Nullable MenuItem item) : boolean
}

class FavoriteModel{
    -favoriteIsTrue: Boolean

    +FavoriteModel(@Nullable Boolean favoriteIsTrue)
}

class FavoriteActivity{
    -favorite_rvAdapter : FavoriteRVAdapter
    -favorite_items : MutableList

    #onCreate(@Nullable bundle savedInstanceState) : void
    +onCreateOptionsMenu(@Nullable Menu menu) : boolean
    +onOptionsItemSelected(@Nullable MenuItem item) : boolean
}

class FavoriteRVAdapter extends Adapter{
    -items : List
    -itemClick : FavoriteRVAdapter.ItemClick
    +onCreateViewHolder(@NotNull ViewGroup parent, int viewType) : FavoriteRVAdapter.ViewHolder
    +onCreateViewHolder(ViewGroup var1, int var2) : androidx.recyclerview.widget.RecyclerView.ViewHolder
    +onBindViewHolder(@NotNull FavoriteRVAdapter.ViewHolder holder, int position) : void
    +onBindViewHolder(androidx.recyclerview.widget.RecyclerView.ViewHolder var1, int var2) : void
    +getItemCount() : int
    +FavoriteRVAdapter(@NotNull List items)
}

class FavoriteRVAdapter_ViewHolder extends androidx.recyclerview.widget.RecyclerView.ViewHolder{
    +ViewHolder(@NotNull View itemView)
    +bindItems(@NotNull String item) : void
}


class CommActivity implements OnNavigationItemSelectedListener{
    -boardDataList : List
    -boardKeyList : List
    -commRVAdapter : CommAdapter
    -setDrawr : boolean
    -nickname : String

    -getFBBoardData() : void
    +onBackPressed() : void
    +onOptionsItemSelected(@NotNull MenuItem item) : boolean
    +onCreateOptionsMenu(@Nullable Menu menu) : boolean
    +onNavigationItemSelected(@NotNull MenuItem item) : boolean
    #onStart() : void
    #onCreate(@Nullable Bundle savedInstanceState) : void
    +setNickname(@Nullable String var1) : void
    +getNickname() : String
}

class BoardInsideActivity {
    -binding : ActivityBoardInsideBinding
    -key : String
    #onCreate(@Nullable Bundle savedInstanceState)
    -getBoardData(String key, boolean isreview)
}

class BoardModel{
    -title: String
    -content: String
    -uid: String
    -time: String
    -nickname: String
    +BoardModel(@NotNull String title, @NotNull String content, @NotNull String uid, @NotNull String time, @NotNull String nickname)
}
class BoardWriteActivity {
    -nickname : String
    #onCreate(@Nullable Bundle savedInstanceState) : void
    #onStart() : void
    +onOptionsItemSelected(@NotNull MenuItem item) : boolean

}


class CommAdapter extends Adapter{
    -items : List

    +onCreateViewHolder(@NotNull ViewGroup parent, int viewType) : CommAdapter.ViewHolder
    +onCreateViewHolder(ViewGroup var1, int var2) : androidx.recyclerview.widget.RecyclerView.ViewHolder
    +onBindViewHolder(@NotNull CommAdapter.ViewHolder holder, int position) : void
    +onBindViewHolder(androidx.recyclerview.widget.RecyclerView.ViewHolder var1, int var2) : void
    +getItemCount() : int
    +CommAdapter(@NotNull List items)
}

class CommAdapter_ViewHolder extends androidx.recyclerview.widget.RecyclerView.ViewHolder{
    -contents : TextView
    -title : TextView
    -nickname : TextView
    -time : TextView
    +ViewHolder(@NotNull View itemView)
    +bindItems(@NotNull String item) : void
}






class ReviewActivity  implements OnNavigationItemSelectedListener{
    -boardDataList : List
    -boardKeyList : List
    -commRVAdapter : CommAdapter
    -setDrawr : boolean
    -nickname : String

    -getFBBoardData() : void
    +onBackPressed() : void
    +onOptionsItemSelected(@NotNull MenuItem item) : boolean
    +onCreateOptionsMenu(@Nullable Menu menu) : boolean
    +onNavigationItemSelected(@NotNull MenuItem item) : boolean
    #onStart() : void
    #onCreate(@Nullable Bundle savedInstanceState) : void
    +setNickname(@Nullable String var1) : void
    +getNickname() : String
}








@enduml